apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
  labels:
    role: api
spec:
  ports:
    - name: http
      port: 3500
      targetPort: 3500
      protocol: TCP
  type: ClusterIP
  selector:
    role: api
